### PR TITLE
Split code based on routes and fix sample requests

### LINKED ISSUE #1: Code splitting
We have an extremely large `app.py` file right now. It'll be great if we can improve code modularity by splitting the file into several files (perhaps one for each endpoint).

### PR DESCRIPTION
**Pull request by sudo-rgorai**
Fixes #1 and #2

### CODE REVIEW

**Comment by sudo-rgorai** [comment]
@sudo-rgorai Isme kaafi major changes hai. Isko jaldi review kardo fir merge kar denge. Uske baad hi koi commits daalna warna achha khaasa merge conflicts aayega

**Review by spookbite — COMMENTED** [review]
Seems good to me. Also, in the golden cross strat, we need to take care of this: "difference b/w start_date and end_date > long_window; long_window > short_window". Apart from this, things seem good enough to me.

**Comment by ooyeraju** [comment]
lgtm

**Comment by sudo-rgorai** [comment]
> In the golden cross strat, we need to take care of this: "difference b/w start_date and end_date > long_window; long_window > short_window".

Will open an issue for this.

**Pull request merged**
